[functions]
  directory = "functions/"

[build.environment]
  NODE_VERSION = "16.17.1"
  AWS_LAMBDA_JS_RUNTIME = "16.17.1"

[[headers]]
  for = "/csv/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/geojson/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/pbf/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://theuscovidatlas.org/"
  to = "https://uscovidatlas.org/"
  force = true

[[redirects]]
  from = "https://theuscovidatlas.org/*"
  to = "https://uscovidatlas.org/:splat"
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
