name: Cypress Tests 0.0.3

on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16


      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install 
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: netlify-build
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: cy:test