name: Cypress Tests 0.0.10

on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup cypress deps
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Install yarn
        run: sudo npm i -g yarn

      - name: Run cypress test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn & yarn netlify-build & yarn cy:test