name: Cypress Tests 0.0.4

on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup cypress deps
      - run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Install Packages
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install 

      - name: Build site
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: netlify-build

      - name: Run test suite
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: cy:test