name: Daily Data Pull 0.1.0c

on:
  schedule:
    - cron: '0 */8 * * *' # runs at midnight, 8am, and 4pm UTC
  workflow_dispatch:

jobs:
  update-data-2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        
      # NODE SETUP
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: install yarn
        run: npm i -g yarn

      - name: install node packages
        run: yarn

      # FETCH BASE DATA
      - name: get data
        run: node build-scripts/fetchLatestData

      # PYTHON SETUP
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r data-scripts/requirements.txt
      
      # PYTHON SCRIPTS
      - name: cdc vaccination data
        run: python data-scripts/cdc/getCdcVaccinationData.py

      - name: cdc county data
        run: python data-scripts/cdc/getCdcCountyData.py

      - name: nyt
        run: python data-scripts/nyt/nyt.py
        
      - name: usafacts
        run: python data-scripts/usafacts/usafacts.py  

      - name: 1p3a
        run: python data-scripts/_1p3a/_1p3a.py  

      - name: hybrid update
        run: python data-scripts/cdc/hybrid_update.py 

      - name: pbf
        run: python data-scripts/pbf/CsvToPbf.py  

      - name: summarize
        run: python data-scripts/summary/summarize.py 

      - name: update report
        run: python weekly-report/update-csvs.py 

      - name: execute update bigquery
        run: python data-scripts/bigquery/update_bigquery.py
        env:
          SK_ID: ${{secrets.GOOGLE_SK_ID}}
          SK: ${{secrets.GOOGLE_SK}}
          G_CLIENT_EMAIL: ${{secrets.GOOGLE_G_CLIENT_EMAIL}}
          G_ID: ${{secrets.GOOGLE_G_ID}}
          G_CERT_URL: ${{secrets.GOOGLE_G_CERT_URL}}
          
      - name: timestamp last-updated
        run: python data-scripts/timestamp/last-updated.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Atlas Bot"
          git add -A
          git commit -m "Update Data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
